import sqlite3
from sklearn.cluster import DBSCAN
import numpy as np
import threading
import cv2

class Database():
    def __init__(self, db_name="contacts"):
        self.db_name = db_name
        self.connection = sqlite3.connect("familiar_contacts.db")
        self.cursor = self.connection.cursor()
        self.rescan_threshold = 13
        self.recan_count = 0
        self.thread = None
        # The following command was generated by CoPilot due to a lack of experience with SQL.
        # The author has thouroughly read through the code and has made changes to fit the vision
        # of the project.
        try:
            self.cursor.execute('''CREATE TABLE IF NOT EXISTS contacts
                                (id INTEGER PRIMARY KEY AUTOINCREMENT,
                                name TEXT NOT NULL,
                                encounter_count INTEGER NOT NULL,
                                image BLOB NOT NULL,
                                last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP)''')
            # https://www.w3schools.com/sql/sql_foreignkey.asp
            self.cursor.execute('''CREATE TABLE IF NOT EXISTS embeddings
                                (id INTEGER PRIMARY KEY AUTOINCREMENT,
                                contact_id INTEGER NOT NULL,
                                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                embedding BLOB NOT NULL,
                                FOREIGN KEY (contact_id) REFERENCES contacts(id))''')
            self.cursor.execute('''CREATE TABLE IF NOT EXISTS unknown_contacts
                                (id INTEGER PRIMARY KEY AUTOINCREMENT,
                                last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                image BLOB,
                                embedding BLOB NOT NULL)''')
            self.connection.commit()
        except sqlite3.Error as e:
            print(f"Error creating table: {e}")
        finally:
            self.connection.close()

    def get_contacts(self):
        try:
            # Connect to database
            self.connection = sqlite3.connect("familiar_contacts.db")
            self.cursor = self.connection.cursor()
            self.cursor.execute('''SELECT name, id, encounter_count, image, last_seen FROM contacts''')
            contact_data = self.cursor.fetchall()
            
            # The following code was generated with the help of CoPilot. The code is used to 
            # decode the images stored as byte strings in the database back into OpenCV images.
            contacts = []
            for contact in contact_data:
                name, contact_id, encounter_count, image_bytes, last_seen = contact
                # Decode the image bytes back into an OpenCV image
                if image_bytes:
                    nparr = np.frombuffer(image_bytes, np.uint8)
                    image = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
                else:
                    image = None
                # Append the contact information to the contacts list
                contacts.append((name, contact_id, encounter_count, image, last_seen))
                
            return contacts
        except sqlite3.Error as e:
            print(f"Error fetching contacts: {e}")
            return []
        finally:
            self.connection.close()


    def get_embeddings(self):
        try:
            # Connect to database
            self.connection = sqlite3.connect("familiar_contacts.db")
            self.cursor = self.connection.cursor()
            self.cursor.execute('''SELECT contact_id, embedding FROM embeddings''')
            face_embeddings = self.cursor.fetchall()
            
            # The following code was generated with the help of CoPilot.
            # Convert the byte string back to a numpy array
            embeddings = []
            contact_ids = []
            for embedding_row in face_embeddings:
                contact_id = embedding_row[0]
                embedding_bytes = embedding_row[1]
                # Convert bytes to numpy array
                embedding_vec = np.frombuffer(embedding_bytes, dtype=np.float64)
                embeddings.append(embedding_vec)
                contact_ids.append(contact_id)
            return contact_ids, embeddings
        except sqlite3.Error as e:
            print(f"Error fetching embeddings: {e}")
            return None, []
        finally:
            self.connection.close()

    def add_unknown(self, embedding, img):
        try:
            self.connection = sqlite3.connect("familiar_contacts.db")
            self.cursor = self.connection.cursor()
            # Encode image into bytes for storage inspired by Copilot code due to lack of experience
            # with SQL and handling storing arrays in databases. I see now that the image needs to be 
            # first encoded into a byte string so that I can be properly docoded from the database.
            success, encoded_image = cv2.imencode('.jpg', img)
            if success:
                image_bytes = encoded_image.tobytes()
            else:
                image_bytes = None
            # Encode the embedding to bytes before storage
            self.cursor.execute('''INSERT INTO unknown_contacts (embedding, image)
                                VALUES (?, ?)''', (embedding.tobytes(), image_bytes))
            self.connection.commit()
        except sqlite3.Error as e:
            print(f"Error adding unknown contact: {e}")
        finally:
            self.connection.close()
            self.recan_count += 1
            if self.recan_count >= self.rescan_threshold:
                self.thread = threading.Thread(target=self.rescan_unknowns)
                self.thread.start()
                self.rescan_threshold = 0

    def add_contact(self, name, embeddings, image):
        try:
            self.connection = sqlite3.connect("familiar_contacts.db")
            self.cursor = self.connection.cursor()
            
            # I was encountering an issue where the images and embeddings were being converted
            # into binary rather than being stored as byte strings. I wasn't sure how to fix this issue,
            # so I used CoPilot built into VSCode to help me understand how to properly convert the images
            # and embeddings into byte strings that could be stored in the database. (No chat link avaliable unfortunately)
            # The code has been understood as it is pretty simple, and it has been modified to better fit 
            # the requirements of the project. 
            success, encoded_image = cv2.imencode('.jpg', image)
            if success:
                image_bytes = encoded_image.tobytes()
            else:
                raise ValueError("Could not encode image")
                
            self.cursor.execute('''INSERT INTO contacts (name, encounter_count, image)
                                VALUES (?, ?, ?)''', (name, 1, image_bytes))
            self.connection.commit()
            new_contact_id = self.cursor.lastrowid
            for embedding in embeddings:
                self.cursor.execute('''INSERT INTO embeddings (contact_id, embedding)
                                    VALUES (?, ?)''', (new_contact_id, embedding.tobytes()))
            self.connection.commit()
        except sqlite3.Error as e:
            print(f"Error adding contact: {e}")
        finally:
            self.connection.close()

    def update_contact(self, contact_id, new_embedding):
        try:
            self.connection = sqlite3.connect("familiar_contacts.db")
            self.cursor = self.connection.cursor()
            # Update the contact's encounter count, last seen timestamp, and image
            self.cursor.execute('''UPDATE contacts
                                SET encounter_count = encounter_count + 1,
                                    last_seen = CURRENT_TIMESTAMP
                                WHERE id = ?''', (int(contact_id),))
            self.connection.commit()
            
            # Add the new embedding to the embeddings table
            self.cursor.execute('''INSERT INTO embeddings (contact_id, embedding)
                                VALUES (?, ?)''', (int(contact_id), new_embedding.tobytes()))
            self.connection.commit()
        except sqlite3.Error as e:
            print(f"Error updating contact: {e}")
        finally:
            self.connection.close()

    def rescan_unknowns(self):
        # Define density based cluster algorithm to use the defined detection threshold
        # and group count. We use the cosine distance formula because it provides good performance for
        # this applications. The use of this function was inspired by the master AI chat. While a code example
        # was provided by the AI, the code was not copied and pasted, but rather used as a reference and adapted
        # based on the style of the programmer and the nuances of the project.
        # https://gemini.google.com/share/ae578f6720c5
        
        # https://scikit-learn.org/stable/modules/generated/sklearn.cluster.DBSCAN.html
        #https://www.geeksforgeeks.org/machine-learning/dbscan-clustering-in-ml-density-based-clustering/
        clustering = DBSCAN(eps=0.2, min_samples=10, metric="cosine")
        new_contacts = {}
        try:
            self.connection = sqlite3.connect("familiar_contacts.db")
            self.cursor = self.connection.cursor()
            # https://www.sqlitetutorial.net/sqlite-select/
            self.cursor.execute(''' 
                                SELECT embedding, image FROM unknown_contacts ORDER BY id
            ''')
            # https://stackoverflow.com/questions/48705926/converting-data-from-sqlite3-database-into-an-array-format
            rows = self.cursor.fetchall()
            
            # Convert the byte string back to a numpy array
            unknown_embeddings = []
            unknown_images = []
            for row in rows:
                embedding_bytes = row[0]
                image_bytes = row[1]
                # Convert bytes to numpy array
                embedding_vec = np.frombuffer(embedding_bytes, dtype=np.float64)
                unknown_embeddings.append((embedding_vec))

                nparr = np.frombuffer(image_bytes, np.uint8)
                image = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
                unknown_images.append(image)

            # If there are unknown embeddings in the table, run the clustering algorithm.
            if len(unknown_embeddings) != 0:
                # Cluster embeddings
                clustering.fit(unknown_embeddings)
                labels = clustering.labels_
                # For every label identified, create a new entry in the new_contacts dictionary
                # with the id of the database entry.
                for idx, label in enumerate(labels):
                    if label != -1:
                        if label not in new_contacts:
                            # Add a new entry to the new_contacts dictionary with the label as the key and the embedding as the value
                            new_contacts[label] = []
                        new_contacts[label].append(unknown_embeddings[idx])


            # Send the new contacts to the UI for confirmation and addition to the contacts table.
            for label, embeddings in new_contacts.items():
                find_image_idx = list(labels).index(label)
                # Display the first image of the new contact for user confirmation
                name = input(f"Please enter a name for the new contact with label {label}: ")
                self.add_contact(name, embeddings, unknown_images[find_image_idx])
                

                # After processing, remove the unknown contacts from the database.
                ##### AI Generated Code Notice #####
                # Generated with the help of CoPilot due to lack of experience with SQL.
                # Code has been throughly reviewed and modified as necessary.
                ##### Code Explanation #####
                # SQL quary is divided into two parts, the delete command, and the find command.
                # First, we start with the find command. Here, we select the id (primary keys) from the unknown_contacts table
                # where the embedding matches the embeddings found in the current index of the new_contacts dictionary.
                # Then, we use those ids to delete the corresponding entries from the unknown_contacts table.
                self.connection = sqlite3.connect("familiar_contacts.db")
                self.cursor = self.connection.cursor()
                embedding_blobs = [np.asarray(embedding, dtype=np.float64).tobytes() for embedding in embeddings]
                self.cursor.execute('''DELETE FROM unknown_contacts
                                    WHERE id IN (SELECT id FROM unknown_contacts
                                    WHERE embedding IN ({}))'''.format(','.join('?' for _ in embedding_blobs)), embedding_blobs)
                self.connection.commit()
        except sqlite3.Error as e:
            print(f"Error rescanning unknown contacts: {e}")
        finally:            
            self.connection.close()


