import sqlite3
from sklearn.cluster import DBSCAN
import numpy as np
import threading
import cv2

class Database():
    def __init__(self, db_name="contacts"):
        self.db_name = db_name
        self.connection = sqlite3.connect("familiar_contacts.db")
        self.cursor = self.connection.cursor()
        self.rescan_threshold = 10
        self.recan_count = 0
        self.thread = None
        # The following command was generated by CoPilot due to a lack of experience with SQL.
        # The author has thouroughly read through the code and has made changes to fit the vision
        # of the project.
        try:
            self.cursor.execute('''CREATE TABLE IF NOT EXISTS contacts
                                (id INTEGER PRIMARY KEY AUTOINCREMENT,
                                name TEXT NOT NULL,
                                encounter_count INTEGER NOT NULL,
                                image, BLOB NOT NULL,
                                last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP)''')
            self.cursor.execute('''CREATE TABLE IF NOT EXISTS embeddings
                                (id INTEGER PRIMARY KEY AUTOINCREMENT,
                                contact_id FOREIGN KEY REFERENCES contacts(id),
                                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                embedding BLOB NOT NULL)''')
            self.cursor.execute('''CREATE TABLE IF NOT EXISTS unknown_contacts
                                (id INTEGER PRIMARY KEY AUTOINCREMENT,
                                last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                image BLOB,
                                embedding BLOB NOT NULL)''')
            self.connection.commit()
        except sqlite3.Error as e:
            print(f"Error creating table: {e}")
        finally:
            self.connection.close()

    def add_unknown(self, embedding, img):
        try:
            self.connection = sqlite3.connect("familiar_contacts.db")
            self.cursor = self.connection.cursor()
            self.cursor.execute('''INSERT INTO unknown_contacts (embedding, image)
                                VALUES (?, ?)''', (embedding, img))
            self.connection.commit()
        except sqlite3.Error as e:
            print(f"Error adding unknown contact: {e}")
        finally:
            self.connection.close()
            self.recan_count += 1
            if self.recan_count >= self.rescan_threshold:
                self.thread = threading.Thread(target=self.rescan_unknowns)
                self.thread.start()
                self.rescan_threshold = 0

    def add_contact(self, name, embeddings, image):
        try:
            self.connection = sqlite3.connect("familiar_contacts.db")
            self.cursor = self.connection.cursor()
            self.cursor.execute('''INSERT INTO contacts (name, encounter_count, image)
                                VALUES (?, ?, ?)''', (name, 1, image))
            self.connection.commit()
            for embedding in embeddings:
                self.cursor.execute('''INSERT INTO embeddings (contact_id, embedding)
                                    VALUES (?, ?)''', (self.cursor.lastrowid, embedding))
            self.connection.commit()
        except sqlite3.Error as e:
            print(f"Error adding contact: {e}")
        finally:
            self.connection.close()

    def rescan_unknowns(self):
        # Define density based cluster algorithm to use the defined detection threshold
        # and group count. We use the cosine distance formula because it provides good performance for
        # this applications.
        clustering = DBSCAN(eps=0.2, min_samples=self.rescan_threshold, metric="cosine")
        new_contacts = {}
        try:
            self.connection = sqlite3.connect("familiar_contacts.db")
            self.cursor = self.connection.cursor()
            self.cursor.execute(''' 
                                SELECT embedding FROM unknown_contacts
            ''')
            unknown_embeddings = self.cursor.fetchall()
            self.cursor.execute(''' SELECT image FROM unknown_contacts ''')
            unknown_images = self.cursor.fetchall()
            # If there are unknown embeddings in the table, run the clustering algorithm.
            if unknown_embeddings:
                # Cluster embeddings
                clustering.fit(unknown_embeddings)
                labels = clustering.labels_
                # For every label identified, create a new entry in the new_contacts dictionary
                # with the id of the database entry.
                for idx, label in enumerate(labels):
                    if label != -1 and label not in new_contacts:
                        new_contacts[label] = []
                    new_contacts[label].append(unknown_embeddings[idx])
            # Send the new contacts to the UI for confirmation and addition to the contacts table.
            for label, embeddings in new_contacts.items():
                # Display the first image of the new contact for user confirmation
                cv2.imshow(f"New Contact Found!", unknown_images[embeddings[0]])
                name = input(f"Please enter a name for the new contact with label {label}: ")
                self.add_contact(name, embeddings, unknown_images[embeddings[0]])
                

                # After processing, remove the unknown contacts from the database.
                ##### AI Generated Code Notice #####
                # Generated with the help of CoPilot due to lack of experience with SQL.
                # Code has been throughly reviewed and modified as necessary.
                ##### Code Explanation #####
                # SQL quary is divided into two parts, the delete command, and the find command.
                # First, we start with the find command. Here, we select the id (primary keys) from the unknown_contacts table
                # where the embedding matches the embeddings found in the current index of the new_contacts dictionary.
                # Then, we use those ids to delete the corresponding entries from the unknown_contacts table.
                self.cursor.execute('''DELETE FROM unknown_contacts
                                    WHERE id IN (SELECT id FROM unknown_contacts
                                    WHERE embedding IN ({}))'''.format(','.join('?' for _ in embeddings)), embeddings)
                self.connection.commit()
        except sqlite3.Error as e:
            print(f"Error rescanning unknown contacts: {e}")
        finally:            
            self.connection.close()



