from datetime import datetime
import sqlite3
from sklearn.cluster import DBSCAN
import numpy as np
import cv2

class Database():
    def __init__(self, db_name="contacts"):
        self.db_name = db_name
        self.connection = sqlite3.connect("familiar_contacts.db")
        self.cursor = self.connection.cursor()
        self.rescan_threshold = 30
        self.recan_count = 0
        # The following command was generated by CoPilot due to a lack of experience with SQL.
        # The author has thouroughly read through the code and has made changes to fit the vision
        # of the project.
        try:
            self.cursor.execute('''CREATE TABLE IF NOT EXISTS contacts
                                (id INTEGER PRIMARY KEY AUTOINCREMENT,
                                name TEXT NOT NULL,
                                encounter_count INTEGER NOT NULL,
                                image BLOB NOT NULL,
                                last_seen TIMESTAMP DEFAULT (datetime('now', 'localtime')))''')
            # https://www.w3schools.com/sql/sql_foreignkey.asp
            self.cursor.execute('''CREATE TABLE IF NOT EXISTS embeddings
                                (id INTEGER PRIMARY KEY AUTOINCREMENT,
                                contact_id INTEGER NOT NULL,
                                created_at TIMESTAMP DEFAULT (datetime('now', 'localtime')),
                                embedding BLOB NOT NULL,
                                FOREIGN KEY (contact_id) REFERENCES contacts(id))''')
            self.cursor.execute('''CREATE TABLE IF NOT EXISTS unknown_contacts
                                (id INTEGER PRIMARY KEY AUTOINCREMENT,
                                last_seen TIMESTAMP DEFAULT (datetime('now', 'localtime')),
                                image BLOB,
                                embedding BLOB NOT NULL)''')
            self.connection.commit()
        except sqlite3.Error as e:
            print(f"Error creating table: {e}")
        finally:
            self.connection.close()

    def get_contacts(self):
        try:
            # Connect to database
            self.connection = sqlite3.connect("familiar_contacts.db")
            self.cursor = self.connection.cursor()
            self.cursor.execute('''SELECT name, id, encounter_count, image, last_seen FROM contacts''')
            contact_data = self.cursor.fetchall()
            
            # Encode image into bytes for storage inspired by Copilot code due to lack of experience
            # with SQL and handling storing arrays in databases. I see now that the image needs to be 
            # first encoded into a byte string so that I can be properly docoded from the database.
            contacts = []
            for contact in contact_data:
                name, contact_id, encounter_count, image_bytes, last_seen = contact
                # Decode the image bytes back into an OpenCV image
                if image_bytes:
                    nparr = np.frombuffer(image_bytes, np.uint8)
                    image = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
                else:
                    image = None
                # Append the contact information to the contacts list
                contacts.append((name, contact_id, encounter_count, image, last_seen))
                
            return contacts
        except sqlite3.Error as e:
            print(f"Error fetching contacts: {e}")
            return []
        finally:
            self.connection.close()


    def get_embeddings(self):
        try:
            # Connect to database
            self.connection = sqlite3.connect("familiar_contacts.db")
            self.cursor = self.connection.cursor()
            self.cursor.execute('''SELECT contact_id, embedding FROM embeddings''')
            face_embeddings = self.cursor.fetchall()
            
            # The following code was generated with the help of CoPilot.
            # Convert the byte string back to a numpy array
            embeddings = []
            contact_ids = []
            for embedding_row in face_embeddings:
                contact_id = embedding_row[0]
                embedding_bytes = embedding_row[1]
                # Convert bytes to numpy array
                embedding_vec = np.frombuffer(embedding_bytes, dtype=np.float64)
                embeddings.append(embedding_vec)
                contact_ids.append(contact_id)
            return contact_ids, embeddings
        except sqlite3.Error as e:
            print(f"Error fetching embeddings: {e}")
            return None, []
        finally:
            self.connection.close()

    def add_unknown(self, embedding, img):
        try:
            self.connection = sqlite3.connect("familiar_contacts.db")
            self.cursor = self.connection.cursor()

            success, encoded_image = cv2.imencode('.jpg', img)
            if success:
                image_bytes = encoded_image.tobytes()
            else:
                image_bytes = None
            # Encode the embedding to bytes before storage
            self.cursor.execute('''INSERT INTO unknown_contacts (embedding, image)
                                VALUES (?, ?)''', (embedding.tobytes(), image_bytes))
            self.connection.commit()
        except sqlite3.Error as e:
            print(f"Error adding unknown contact: {e}")
        finally:
            self.connection.close()
            self.recan_count += 1
            if self.recan_count >= self.rescan_threshold:
                self.rescan_threshold = 0

    def add_contact(self, name, contact_data, image):
        try:
            self.connection = sqlite3.connect("familiar_contacts.db")
            self.cursor = self.connection.cursor()
            embeddings, created_at = contact_data
            # I was encountering an issue where the images and embeddings were being converted
            # into binary rather than being stored as byte strings. I wasn't sure how to fix this issue,
            # so I used CoPilot built into VSCode to help me understand how to properly convert the images
            # and embeddings into byte strings that could be stored in the database. (No chat link avaliable unfortunately)
            # The code has been understood as it is pretty simple, and it has been modified to better fit 
            # the requirements of the project. 
            success, encoded_image = cv2.imencode('.jpg', image)
            if success:
                image_bytes = encoded_image.tobytes()
            else:
                raise ValueError("Could not encode image")
                
            self.cursor.execute('''INSERT INTO contacts (name, encounter_count, image)
                                VALUES (?, ?, ?)''', (name, 1, image_bytes))
            self.connection.commit()
            new_contact_id = self.cursor.lastrowid
            for idx in range(len(embeddings)):
                self.cursor.execute('''INSERT INTO embeddings (contact_id, embedding, created_at)
                                    VALUES (?, ?, ?)''', (new_contact_id, embeddings[idx].tobytes(), created_at[idx]))
            self.connection.commit()
        except sqlite3.Error as e:
            print(f"Error adding contact: {e}")
        finally:
            self.connection.close()

    def update_contact(self, contact_id, new_embedding=None):
        try:
            self.connection = sqlite3.connect("familiar_contacts.db")
            self.cursor = self.connection.cursor()
            self.cursor.execute('''UPDATE contacts
                                SET encounter_count = encounter_count + 1,
                                    last_seen = (datetime('now', 'localtime'))
                                WHERE id = ?''', (int(contact_id),))
            self.connection.commit()

            self.cursor.execute('''SELECT last_seen FROM contacts WHERE id = ?''', (int(contact_id),))
            last_seen = self.cursor.fetchone()[0]
            self.cursor.execute('''SELECT created_at FROM embeddings WHERE contact_id = ? ORDER BY created_at DESC LIMIT 1''', (int(contact_id),))
            last_embedding_time = self.cursor.fetchone()[0]
            print(f"Contact {contact_id} last seen at {last_seen}, last embedding added at {last_embedding_time}")  

            date_format = "%Y-%m-%d %H:%M:%S"
            current_date = datetime.strptime(last_seen, date_format)
            last_embedding_date = datetime.strptime(last_embedding_time, date_format)
            time_diff = (current_date - last_embedding_date).total_seconds()
            if time_diff > 10 and new_embedding is not None: # 24 hours
                print(f"Adding new embedding for contact {contact_id} due to time difference of {time_diff} seconds.")
                self.cursor.execute('''SELECT created_at FROM embeddings WHERE contact_id = ? ORDER BY created_at ASC LIMIT 1''', (int(contact_id),))
                oldest_embedding_time = self.cursor.fetchone()[0]
                self.cursor.execute('''DELETE FROM embeddings WHERE created_at = ? AND contact_id = ?''', (oldest_embedding_time, int(contact_id)))
                self.cursor.execute('''INSERT INTO embeddings (contact_id, embedding)
                                    VALUES (?, ?)''', (int(contact_id), new_embedding.tobytes()))
                self.connection.commit()
        except sqlite3.Error as e:
            print(f"Error updating contact: {e}")
        finally:
            self.connection.close()

    def rescan_unknowns(self):
        # Define density based cluster algorithm to use the defined detection threshold
        # and group count. We use the cosine distance formula because it provides good performance for
        # this applications. The use of this function was inspired by the master AI chat. While a code example
        # was provided by the AI, the code was not copied and pasted, but rather used as a reference and adapted
        # based on the style of the programmer and the nuances of the project.
        # https://gemini.google.com/share/ae578f6720c5
        
        # https://scikit-learn.org/stable/modules/generated/sklearn.cluster.DBSCAN.html
        #https://www.geeksforgeeks.org/machine-learning/dbscan-clustering-in-ml-density-based-clustering/
        clustering = DBSCAN(eps=0.2, min_samples=10, metric="cosine")
        new_contacts = {}
        try:
            self.connection = sqlite3.connect("familiar_contacts.db")
            self.cursor = self.connection.cursor()
            # https://www.sqlitetutorial.net/sqlite-select/
            self.cursor.execute(''' 
                                SELECT embedding, image, last_seen FROM unknown_contacts ORDER BY id
            ''')
            # https://stackoverflow.com/questions/48705926/converting-data-from-sqlite3-database-into-an-array-format
            rows = self.cursor.fetchall()
            
            # Convert the byte string back to a numpy array
            unknown_embeddings = []
            unknown_images = []
            unknown_dates = []
            for row in rows:
                embedding_bytes = row[0]
                image_bytes = row[1]
                unknown_dates.append(row[2])
                # Convert bytes to numpy array
                embedding_vec = np.frombuffer(embedding_bytes, dtype=np.float64)
                unknown_embeddings.append((embedding_vec))

                nparr = np.frombuffer(image_bytes, np.uint8)
                image = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
                unknown_images.append(image)

            # If there are unknown embeddings in the table, run the clustering algorithm.
            if len(unknown_embeddings) != 0:
                # Cluster embeddings
                clustering.fit(unknown_embeddings)
                labels = clustering.labels_
                # For every label identified, create a new entry in the new_contacts dictionary
                # with the id of the database entry.
                for idx, label in enumerate(labels):
                    if label != -1:
                        if label not in new_contacts:
                            # Add a new entry to the new_contacts dictionary with the label as the key and the embedding as the value
                            new_contacts[label] = []
                        new_contacts[label].append(unknown_embeddings[idx])


            # Send the new contacts to the UI for confirmation and addition to the contacts table.
            pending_contact_approvals = []
            if len(unknown_embeddings) != 0:
                for label, embeddings in new_contacts.items():
                    find_image_idx = list(labels).index(label)
                    image = unknown_images[find_image_idx]
                    pending_contact_approvals.append({
                        "embeddings": embeddings,
                        "image": image,
                        "created_at": unknown_dates
                    })
                return pending_contact_approvals
                    
        except sqlite3.Error as e:
            print(f"Error rescanning unknown contacts: {e}")
        finally:            
            self.connection.close()


    def clean_unknowns(self, embeddings):
        try:
            self.connection = sqlite3.connect("familiar_contacts.db")
            self.cursor = self.connection.cursor()
            # Next two lines suggested by VSCode CoPilot. They were the same as what I was going to write,
            # but accounted for the embeddings being stored as byte strings and the unknown of removing items from a list
            # in SQL query.
            embedding_blobs = [np.asarray(embedding, dtype=np.float64).tobytes() for embedding in embeddings]
            self.cursor.execute('''DELETE FROM unknown_contacts WHERE embedding IN ({})'''.format(','.join('?' for _ in embedding_blobs)), embedding_blobs)
            self.connection.commit()
            print(f"Cleaned {len(embeddings)} unknown contacts from the database.")
        except sqlite3.Error as e:
            print(f"Error cleaning unknown contacts: {e}")
        finally:
            self.connection.close()


